---
- name: Download OpenShift CLI
  get_url:
    url: "https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz"
    dest: "/tmp/oc.tar.gz"
  become: yes

- name: Extract OpenShift CLI
  unarchive:
    src: "/tmp/oc.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: yes
  become: yes

- name: Verify OpenShift CLI Installation
  command: oc version
  register: oc_version

- name: Display OpenShift CLI Version
  debug:
    msg: "{{ oc_version.stdout }}"

# tasks file for openshift
