pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/IbrahimAdell/App1.git'
            }
        }
        stage('Docker image') {
            steps {
				withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                sh """
				docker build . -t lab22-image
				docker login -u ${USERNAME} -P ${PASSWORD}
				docker push lab22-image
				docker rmi lab22-image
				"""
                }
            }
        }
        stage(' Deployment on k8s ') {
            steps {
                script {
                    sh """
					sed -i 's|image: .*|image: ${DOCKER_IMAGE}|' ${DEPLOYMENT_FILE}
					kubectl apply -f ${DEPLOYMENT_FILE}
					"""
                }
            }
        }
	}
	
}
