apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3-deployment
  namespace: REPLACE_NAMESPACE  # This will be replaced dynamically
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
        - name: app3
          image: REPLACE_IMAGE  # This will be replaced dynamically
          imagePullPolicy: Always  # Ensure it always pulls the latest image
          command: ["/bin/sh", "-c", "echo 'Hello'; sleep 99999999"]
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app3-service
  namespace: REPLACE_NAMESPACE
spec:
  selector:
    app: app3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
